### ISSUE TITLE
ddu設定不具合まとめ

### ISSUE THREAD

**Issue by kyoh86** [kyoh86/dotfiles#59]
何かの拍子におかしくなることがある。最近設定見れてないから陳腐化している影響だと思う。

発生している事象だけまとめ。
どうもNxをTerminalでnpm runしてる最中に起きるが、因果関係があるかは今のところ不明。僕の作ってる即席ターミナルの動きが悪いかも。

- フィルタに入力する度にnormal modeに戻る
- フィルタに入力する度にカーソル位置が別の行（フィルタ入力バッファ内の過去の入力）に移動してしまう
- ddu-source-bufferを開くと、terminalバッファがdduのWindowを乗っ取ってしまう（Previewが流れ込んできてしまう？）

**Comment by Shougo** [comment]
最小構成を作ったほうがよいですね。これは

他のプラグインや設定が悪さしていると思うので。

**Comment by Shougo** [comment]
> ddu-source-bufferを開くと、terminalバッファがdduのWindowを乗っ取ってしまう（Previewが流れ込んできてしまう？）

これはさっぱり分からないですね

**Comment by kyoh86** [comment]
> ddu-source-bufferを開くと、terminalバッファがdduのWindowを乗っ取ってしまう（Previewが流れ込んできてしまう？）

これはterminalのタイトルを取る処理が適当すぎて、色んなバッファにbuffer.ensureしてタイトル取って…を繰り返すのにbatch噛ましてなかったから。処理に割り込んでしまっていた。

**Comment by kyoh86** [comment]
> フィルタに入力する度にカーソル位置が別の行（フィルタ入力バッファ内の過去の入力）に移動してしまう

これはマジで再現条件がよく分からないんだよな…「しばらく使ってると起きる」系だから、明らかにddu単体と言うより、「たまに動く他の何か」が干渉している感がある。
そうなると、最小再現条件がキツい。試行時間が長くなるからな…

起きたときに見るべきモノを洗っておいた方がよさそう。じゃないと当たりすら付かないので厳しすぎる。
長時間使ってると発生するバグはこの辺の調査ノウハウが難しいんだよなー。

- keymapがイカれてないか
- バッファの中身に変なもんが入ってないか
- autocmdに変なもんが入ってないか

**Comment by kyoh86** [comment]
あとはやっぱりdduの設定を自分で壊してしまってる可能性はあるので、起きた時点でのglobal/localのconfigはdumpしておきたい。

**Comment by kyoh86** [comment]
今のところ発生する契機として思ってることは

- 長時間起動したNeovimで色々触った時にしかおきない
- 特に編集作業が複数プロジェクトにまたいでいる可能性が高い（こと”何か" + dotfiles）と思う（多分）
- フィルタの起動をトチったことがあると起きやすい気もする（keymapより先に `/` 押しちゃってコマンドラインモードに入って…みたいな）

事象的には

フィルタに誤入力を与えてしまったので消して書き直す、みたいな操作をしているときに、
何故か入力が上手くいかず、過去に入力したフィルタの内容が復活してきてる？（ように見える）
おそらくバッファ内のカーソル制御が狂ったせいで変な移動をしてるとかなんだけど、imapとか見ないと何とも言えない部分は大きい。
だいたい煮詰まってるときに起きるので、今見てる場合じゃないんだわ、とNeovim再起動してるから事象と条件がマジでちゃんと観察できてない。

**Comment by kyoh86** [comment]
補完とかabbrの設定を変なタイミングで呼んじゃってるのかもなあ。とかくやはりまずは情報収集。

- keymap（ことimap）がイカれてないか

も見よう

**Comment by kyoh86** [comment]
```
        imap("<bs>", function()
          return vim.fn.col(".") <= 1 and "" or "<bs>"
        end, { expr = true, remap = true })
```

あーこれ悪そう。FileType ddu-ff-filterで設定してるから、expr=true + remap=trueでこんなことしたら、何かの拍子におかしくなる気はする。

**Comment by kyoh86** [comment]
とりあえずこれはremap = true外しておいてみる。

**Comment by kyoh86** [comment]
突然Normalになる問題はターミナルの解消で解決した

**Comment by kyoh86** [comment]
ff-filterでのカーソル暴走もぐっと減った感じがする。いったんCloseしておこう。remapとexprでmapするのムズい
